version: "3.9"

services:
  drs_api:
    container_name: drs_api
    image: drs_img
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@drs_db:5432/postgres
    depends_on:
      - drs_db
  drs_db:
    container_name: drs_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
